### ISSUE TITLE
Can't build it

### ISSUE THREAD

**Issue by MichalMisiaszek** [lcallarec/live-chart#22] opened 2020-10-19 17:29 UTC
michal@edhnuc:~/Downloads/live-chart-master$ meson build
The Meson build system
Version: 0.45.1
Source dir: /home/michal/Downloads/live-chart-master
Build dir: /home/michal/Downloads/live-chart-master/build
Build type: native build
Project name: live-chart
Native C compiler: cc (gcc 7.5.0 "cc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0")
Native Vala compiler: valac (valac 0.40.23)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Library m found: YES
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency gtk+-3.0 found: YES 3.22.30
Native dependency gee-0.8 found: YES 0.20.1

meson.build:11:3: ERROR: Tried to access unknown option "debug".

**Comment by lcallarec** [comment] 2020-10-20 22:39
Thanks for this issue.

Meson `0.45.1` is pretty old ; built-in debug options wasn't implemented yet.

https://github.com/lcallarec/live-chart/commit/6973bf8a3683994255947f3f85aa80c37f9e29d3 on master should fix your issue, could you please check and close this issue when it's ok ?

**Comment by lcallarec** [comment] 2020-11-23 08:17
@MichalMisiaszek I close the issue, but I have not tested so much on meson 0.45.1. Feel free to reopen if the issue is still there.

**Closed by lcallarec** 2020-11-23 08:17 UTC
